joule-labs/joule-extension

src/content_script/index.ts

Closes #10. Very simple document click selector. I'd like to have used something more sophisticated like the extension webRequest API, but there is **_no support_** for custom protocols. So alas, here we are.

Intercept Lightning URIs

---

src/app/components/AccountInfo/DepositModal.less
src/app/components/AccountInfo/DepositModal.tsx
src/app/components/Copy.tsx
src/app/components/PasswordPrompt/index.tsx
src/app/lib/lnd-http/index.ts
src/app/modules/account/actions.ts
src/app/modules/account/reducers.ts
src/app/modules/account/sagas.ts
src/app/modules/account/types.ts
src/app/modules/payment/sagas.ts
src/app/typings/react-copy-to-clipboard.d.ts

Implements the deposit address modal. Unfortunately getting at the address is behind the admin macaroon, for some reason, so it requires a password entry.
Somewhere along the way I fixed #20 as well.
<sup>Feel free to uh, deposit some BTC to that one if you'd like.</sup>

Deposit address modal

---

src/app/components/SelectNode/InputAddress.less
src/app/components/SelectNode/InputAddress.tsx
src/app/components/SelectNode/index.tsx

Closes #19.
Improves the experience for users connecting to nodes (mainly local) that have self-signed certificates. It displays some text that explains what the error may be, and how to solve it. Unfortunately, there is no granularity to the information of why a requests failed (We just get "TypeError: Failed to fetch" which is the same error you get for many reasons.) So we just display the help text no matter what.
It's also worth noting that the instructions @brandoncurtis provided in #19 seemed to be OS-specific, so I went for the quick-and-easy approach of just telling the user to have the browser ignore the cert issue.
Ideally, this issue will be solvable in the future with either better extension permissions (Just ignore the cert error) or some better ssl cert procedure during lnd …

SSL cert error instructions

---

src/app/components/AccountInfo/index.tsx
src/app/components/AccountInfo/style.less
src/app/components/ChannelList/ChannelRow.less
src/app/components/ChannelList/ChannelRow.tsx
src/app/components/TransactionList/TransactionRow.tsx
src/app/components/TransactionList/index.tsx
src/app/components/Unit.tsx
src/app/lib/lnd-http/index.ts
src/app/modules/account/sagas.ts
src/app/modules/account/types.ts
src/app/pages/home.tsx

Mostly prep-work for #3 & #4, wraps most components in the `<Unit/>` component and comma-ifies them. Somewhat improves the interface of channel balances.
Also temporarily disables the unfunctioning channel drawer on click, since it wasn't doing anything. That'll be re-added in full with a future PR.

Better balances

---

src/app/components/Settings/index.tsx
src/app/modules/crypto/reducers.ts
src/app/modules/node/reducers.ts
src/app/modules/settings/actions.ts
src/app/modules/settings/types.ts
src/app/utils/crypto.ts

Adds a button to the settings menu that resets your node & password. In the future, we'll probably want a more elegant user swap behavior, but this'll do for now.

Reset connection settings

---

src/content_script/injectScript.ts
static/manifest.json

Closes #52. Injects WebLN at `document_start` instead of `document_end`.

Faster WebLN Inject

---

src/content_script/index.ts

Fixes a bug introduced in #53 that stopped the click bolt-11 links from working. Waits for domcontentloaded before attempting to bind.

FIX: bolt-11 links

---

src/app/components/SelectNode/UploadMacaroons.less
src/app/components/SelectNode/UploadMacaroons.tsx

Closes #58.
Allows for the input of raw hex strings for macaroons, instead of file uploads. Togglable by clicking a link towards the bottom. This probably won't be the final UX for BTCPay Server users (And any other clients that expose macaroons as a hex string,) but this makes it possible to setup in the short term.
1. Spin up a BTCPay Server
2. Navigate to `/server/services/lnd-rest/BTC/1`
3. Setup Joule using your REST API endpoint and macaroon hex string

Allow macaroon hex string input

---

src/content_script/runSelector.ts

Fixes an issue where an empty settings state (e.g. you just installed and never changed settings) cause `webln.enable()` calls to fail. This will require a v0.2.1 release.

[FIX] Errorous settings state on enable

---

src/app/components/ChannelList/ChannelRow.less
src/app/components/ChannelList/ChannelRow.tsx

This pull request adds channel progress bars to the channel overview.
Let me know what you think, I can make changes to the style if needed. This also adds Bootstrap to the Project so if this is not wanted, I can try to accomplish the task in a different way.
There is still one bug in this which I don't understand:
When the plugin is clicked the Channel Balance does not display, only if you maximize the window or e.g. click on settings and then it shows up. If someone knows how to fix it I would be grateful.

Channel progress bars

---

src/app/PromptRoutes.tsx
src/app/components/PromptTemplate/index.tsx
src/app/prompts/onboarding.less
src/app/prompts/onboarding.tsx
src/content_script/index.ts

Closes #6, sorta.
Rather than not inject WebLN if you don't have Joule configured, this changes it so that you get a prompt to onboard each time instead. This provides the user with better feedback than the current error message behavior.
1. Clear node connection settings
2. Go to a WebLN enabled website, or click on a BOLT-11 link
3. Confirm you get an onboarding prompt
4. Click and complete the onboarding
5. Either refresh the page, or click the BOLT-11 link again. Confirm it works as normal.

Onboarding prompt

---

src/app/components/SelectNode/BTCPayServer.less
src/app/components/SelectNode/BTCPayServer.tsx
src/app/components/SelectNode/SelectType.tsx
src/app/components/SelectNode/index.tsx
src/app/lib/lnd-http/index.ts
src/app/static/images/btcpayserver.svg
src/app/utils/background.ts

Closes #79. Will want a review from @NicolasDorier on this one.
Adds an option to the node selector for BTCPay Server. Uses the BTCPay Server config format for filling out URI & macaroons.
1. Setup a BTCPay Server
2. Go through Joule onboarding, select BTCPay Server
3. Follow the instructions and fill out the config data
4. Confirm you connect correctly
^Click to embiggen

BTCPay Server onboarding

---

src/app/components/SelectNode/InputAddress.tsx

Triage for #99, but not a fix.
Adds a warning when you have a failed connection on Firefox that explains the current CORS issue described in #99. This will hopefully be removed as soon as either Firefox or LND addresses this issue, or I find a good work-around.
1. Run through onboarding in Firefox
2. Select "local node" as your node type
3. Confirm you see the warning if you see the error message

Firefox CORS warning

---

static/manifest.json

This fix repairs the missing icon in the toolbar
Relevant documentation: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action

Firefox: fix missing icon in the toolbar

---

README.md
src/options/template.html
src/popup/template.html
src/prompt/template.html
webpack.config.js

Closes #114 
Adds the ability for developers to use the standalone React Dev Tools to inspect the virtual dom of each of the extension pages.
1. Run `npm install -g react-devtools`
2. Be sure to use `yarn run dev` to build the app
2. Run `react-devtools` in a new Terminal
3. A new window will open displaying the React vdom inspector

Add support for React Dev Tools

---

src/app/components/InvoiceForm/index.tsx
src/app/components/InvoiceForm/style.less
src/app/components/Loader.tsx
src/app/components/SendForm/LightningSend.less
src/app/components/SendForm/LightningSend.tsx
src/app/components/TransactionInfo/index.tsx
src/app/components/TransactionInfo/style.less
src/app/components/TransactionList/index.tsx
src/app/lib/lnd-http/types.ts
src/app/modules/payment/actions.ts
src/app/modules/payment/reducers.ts
src/app/modules/payment/sagas.ts
src/app/prompts/payment.less
src/app/prompts/payment.tsx

Closes #75
Allows the creation, viewing, and payment of invoices without an amount specified. The `makeInvoice` prompt, however, does not have the ability to do this, due to the WebLN spec not accounting for this (discussion for that over here https://github.com/wbobeirne/webln/issues/13)
I've created #118 since this introduces a hefty amount of copy-paste for amount inputs. I hate to kick this can down the road, but I didn't want to have to change _too_ much to get this working right now.
1. Generate an invoice, and check the "any amount" checkbox. Confirm invoice is created without amount specified
* You can check on https://lndecode.com/
2. Make a payment using a BOLT-11 link or WebLN that has no amount specified. Confirm you had to specify the amount in the prompt, and that it worked. …

Any amount invoice creation & payments

---

src/app/modules/account/sagas.ts
src/app/modules/channels/sagas.ts
src/app/utils/misc.ts

No issue opened, but a couple of folks reported this one.
Provides a fallback stubbed node object in cases where the node we fetch more info about is offline.
1. Make a transaction with a node you control
2. Disconnect that node from the network
3. Load your transactions, and confirm that it displays as `<Offline node>`

Handle offline nodes on transactions and channels list

---

README.md
package.json
src/app/AppRoutes.tsx
src/app/PromptRoutes.tsx
src/util/hotserver.js
webpack.config.js
yarn.lock

Closes #125 
Adds React Hot Reload functionality to the development environment. No modifications are made to production builds. This simply improves the feedback loop of seeing changes 
1. Run `yarn run hot`
2. Load the extension in Chrome
3. Click on the toolbar icon to open the popup
4. Click on the *Invoice* button to open the drawer
5. Type any number in the *Amount* field
6. In your code editor, open the InvoiceForm.tsx file
7. Change the *Amount* label to *Payment Amount* then Save the file
8. Observe in the browser that the label updates but the state of the component remained unchanged
This is not 100% ready to be merged, but I wanted to put it out there for now. I need to test browsers other than Chrome to make sure nothing is broken.

Add React Hot Reload

---

src/app/components/Splash/index.tsx

Closes #110 
Pretty simple update to skip the redundant splash screen when the `Get Started` button is clicked on the popup.
1. Reset your connection settings to restart the onboarding process
2. Click on the Joule toolbar icon
3. Click on the `Get Started` button
4. Confirm the full page tab shows the Choose node screen
I used `browser.storage.local` to pass the `skipSplash` flag to the full page from the popup. This ended up being the simplest solution. 
I first thought to pass a querystring param to the options page but this isn't possible unless you manually create a new tab with `browser.tabs.create({ url: browser.extension.getURL('options.html') });`. This would require the `tabs` permission so I knew that wouldn't be a good choice. 
I also thought to use the background script to …

Skip Splash screen when onboarding opens in full page

---

src/content_script/runSelector.ts

Closes #144
Fixes `runSelector` not properly retrieving new versioned data from from browser storage. The issue #144 has a detailed explanation of the problem.
1. Visit a website that has WebLN support such as lightningspin.com or tippin.me (login required)
2. When the page loads, the Joule authorization prompt will popup
3. Ensure `Remember my choice` is checked
4. Click on `Confirm`
5. Refresh the website
6. Ensure the authorize popup is not displayed
7. Open the browser devtools console and type `webln.isEnabled`
8. Confirm the value `true` is displayed

Fix incorrect storage data retrieved by prompts

---

src/app/components/SelectNode/ConfirmNode.tsx

No associated issue
Just a quick one, shows which chain your node is on the confirm screen.
1. Go through onboarding, confirm it shows the right chain for your node.

Show chain on node confirm screen

---

src/app/modules/sync/sagas.ts
src/app/utils/sync.ts

Addendum to #142. I found that after merging that one in, I was actually getting the problem that that PR was meant to fix. The issue is that you can potentially have two states in local storage for the encrypted node data, either the old flat style:
```
node-encryped | 'U2FsdGVkX1/DLtlI...'
```
or the new style with a version number
```
node-encryped | '{"data": "U2FsdGVkX1/DLtlI...", "version": 1}'
```
While unencrypted storage items had this problem as well, we are running them through `migrateSyncedData` which normalizes them to the new style. Encrypted data was _not_ being run through though, since it couldn't be migrated. This change runs it through migration anyway, but bails out if it detects that it's still encrypted. This should fix any and all remaining issues around them not …

Fix decryptSyncedData raising an error (Pt. 2)

---

src/app/lib/lnd-http/index.ts

Fixes a small issue I noticed where some transactions don't send an `amount` field. I'm not sure what these transactions are, but I've gone ahead and given it a default of `"0"` just to stop the crashing. Perhaps these transactions should be removed or displayed differently though.

Fix transactions with no amount field causing a crash

---

src/app/components/ChannelList/index.tsx

Closes #164 
Added a button to the BigMessage in ChannelList that shows an OpenChannelModal upon click. This button is only shown when the ChannelList is empty.
1. Click the button
2. Admire the opening of a ChannelModal

Added Open Channel button to empty Channel List

---

src/app/lib/lnd-http/index.ts

Closes #163 
Fixes the bug described in the issue referenced above.
**Technical**
We were not mapping the top-level keys of the response objects so we discarded all of the data except `remote_balance`, `local_balance` & `capacity` from the `channel` nested object. I changed the code to merge the top-level with the nested keys while mapping the response.
1. Force-close one of your channels
2. Hover over the orange icon in the channel list
3. Confirm the tooltip shows the number of blocks as non-zero

Fix blocks_til_maturity not showing in the UI

---

src/app/utils/constants.ts

Add Russian rubble currency
1. Click `Settings`
2. Select `RUB` in the `currency` selector
3. Got to the main screen and check fiat value

Add Russian ruble fiat

---

src/app/lib/lnd-http/index.ts

Closes #187
Defaults utxos response to empty array so that utxos aren't false-y after the request has been made.
1. Spin up a clean node or spend all of your UTXOs
2. Attempt to load the balance page
3. Success!

Default empty array for utxos

---

package.json
webpack.config.js
yarn.lock

Untracked issue
Updates ant-design-pro and webpack-dev-server due to vulnerabilities. Also nix'd an unused module require in webpack conf that relied on being a subdependency that no longer exists.
Just use the extension, make sure the upgrades didn't do anything too crazy

Update vulnerable packages

---

src/app/components/ChannelInfo/index.less
src/app/components/ChannelInfo/index.tsx

Untracked issue
Due to the outstanding issue of being unable to close a channel via the REST API, I figured a good middleground would be to at least include instructions on how to close a channel via the CLI. This adds an input and copy button of how to close the channel at the bottom of the details menu.
1. Click on an open channel
2. Confirm you get valid close instructions
3. Click on a non-open channel
4. Confirm close instructions don't render

Add channel close instructions

---

package.json
src/app/components/Balances/index.tsx
src/app/components/SelectNode/SelectType.less
src/app/components/SelectNode/SelectType.tsx
src/app/static/images/zap.svg
src/app/utils/constants.ts
webpack.config.js
yarn.lock

Closes #158
Adds a zap option to onboarding. Auto-connects to the 8180 port, and shows paths for the macaroons where Zap saves them. It's a little tricker, because zap supports multiple wallets and requires more rooting around in the file system. Hopefully there will be an easier way to get at these in the future.
Also fixes an issue with svgr that caused id collisions in svgs for things like gradients, and bumps up the icons a bit on the node type selection.
1. Run zap
2. Onboard with the zap option
3. Confirm it works as expected

Zap onboarding button

---

src/app/components/AccountInfo/index.tsx
src/app/components/AccountInfo/style.less

Closes #199
Adds a banner when your node is still syncing to the chain to let you know that your balances might be off. To my knowledge there's no way to get progress, since it always reports the bitcoin node's block height, not LND's current scan progress, so the best we can do is this boolean display.
Open joule with a syncing node (or induce the state yourself programmatically), confirm you see a banner.

Sync warning

---

src/app/components/SelectNode/InputAddress.tsx

Closes #198 
Modified InputAddress.tsx 'submittedUrl' value in the state. The submitted URL is decomposed and only the host and port are extracted. Any additional characters after the port number are removed and joined with remaining test URL /v1/getinfo.
1. Clear browser history
2. Begin to setup the Joule Extension
3. Enter URL with trailing foward slash on the Failed to connect screen
4. Verify no additional slashes are added

Fixed Connection problem URL formats  #198

---

src/app/components/Identicon.tsx
src/app/components/TransactionInfo/index.tsx
src/app/components/TransactionInfo/style.less
src/app/components/TransactionList/TransactionRow.tsx
src/app/lib/lnd-http/index.ts
src/app/modules/account/sagas.ts
src/app/utils/misc.ts

Closes #206
Fixes some payments (I think only quite old ones) from crashing the transactions tab. This happened due to them coming back with `undefined` paths. In total, this PR does the following:
* Defaults the `path` array to `[]` if undefined
* Improves the display of pathless payments
* Improves the Identicon component by having it display a (?) when the pubkey is falsy
1. Get a pathless payment, or alter the code so that you can forcefully induce one
2. Load the transactions tab, confirm it doesn't crash
3. Open a pathless transaction, confirm it displays correctly

Fix pathless transactions crashing tx list

---

src/app/components/ChannelList/ChannelRow.less
src/app/components/ChannelList/ChannelRow.tsx
src/app/components/Help/index.less
src/app/components/Help/index.tsx
src/app/components/InvoiceForm/index.tsx
src/app/components/InvoiceForm/style.less
src/app/components/SendForm/LightningSend.tsx
src/app/components/Unit.tsx
src/app/lib/lnd-http/types.ts
src/app/modules/payment/sagas.ts
src/app/prompts/invoice.less
src/app/prompts/invoice.tsx
src/app/style.less

Closes #192 
This makes invoice creations include private route hints, and also works around the issue where you were unable to send invoices that relied on private routes due to QueryRoute's inability to take in routing hints, and Joule's running of QueryRoutes before letting a user send to ensure that there _is_ a route and to provide the user fee information before they send.
The latter part of this should be moot as soon as this PR is merged https://github.com/lightningnetwork/lnd/pull/2186 but even then will stay an issue for folks running older node versions for a while. This janky temporary fix of returning placeholder routing info will probably have to sit in for a while until there's a reasonable expectation that most people have upgraded.
I also make a `Help` component and used …

Provide private channel route hints & make private routes sendable

---

src/app/utils/units.ts

Closes #223 
The change is very simple and local: the structure containing the number of decimal points in the representation of a bitcoin amount at that denomination had two numbers swapped.  I unswapped them.

fixes bits/mBTC inversion

---

src/app/components/PromptTemplate/index.tsx
src/app/components/PromptTemplate/style.less

Closes #227
Changes prompt errors from `message.error` which would disappear automatically, to rendering an `<Alert />` that the user has to manually dismiss. Doesn't look quite as nice, but should be a lot better for longer errors or when the user backgrounds the window and comes back later.
1. Go to https://webln.dev/#/api/make-invoice
2. Make an invoice of a number way too high
3. Confirm you get an error
4. Confirm the error doesn't disappear automatically
5. Confirm clicking on the X dismisses the error

Better errors for WebLN prompts

---

src/app/modules/appconf/types.ts
src/app/utils/constants.ts
src/content_script/respondWithoutPrompt.ts

So far the `lastPaymentAttempt` is not presisted yet and thus the cooldown period for an allowance could not be calculated. 
This change stores the `lastPaymentAttempt` timestamp as part of the allowance config. The default value is 0 as before.

Store last payment attempt in the allowance config

---

README.md

Seems the readme is using DOS line encodings. I think it is common practice to use unix line breaks (which are also supported by windows editors, afaik?)
This PR did a `dos2unix README.md`

Convert readme to use unix line breaks

---

.github/workflows/build.yml

This GitHub workflow runs a production build on every push to the develop branch (e.g. whenever a pull request is merged) and whenever a version tag is created.
The build artifacts are stored and made available for download. 
You can see the workflow in action here: https://github.com/bumi/joule-extension/actions/runs/346573887

Add GitHub workflow to run build:prod
